# 就业参数配置文件
# 基于容量因子计算各行业就业人数

industries:
  Aluminum:
    installed_capacity: 18.5  # Mt - 铝冶炼厂装机容量
    employment_per_mt: 15.4   # k/Mt - 每Mt装机对应的就业人数
    display_name: "铝冶炼厂"
    unit_system: "Mt"
  
  Coal:
    installed_capacity: 328.0  # GW - 煤电装机容量
    employment_per_gw: 0.5     # k/GW - 每GW装机对应的就业人数
    display_name: "煤电"
    unit_system: "GW"
  
  Gas:
    installed_capacity: 100.80  # GW - 天然气发电装机容量
    employment_per_gw: 0.2      # k/GW - 每GW装机对应的就业人数
    display_name: "天然气发电"
    unit_system: "GW"

# 绘图配置
plot:
  figure_size: [12, 8]
  dpi: 150
  font_size: 18
  legend_font_size: 20
  title_font_size: 24
  axis_font_size: 24

# 颜色配置
colors:
  铝冶炼厂: "#FF69B4"    # Hot pink
  煤电: "#000000"        # Black
  天然气发电: "#FF0000"  # Red

# 输出配置
output:
  directory: "results/employment_analysis"
