# 就业参数配置文件
# 基于容量因子计算各行业就业人数

industries:
  Aluminum:
    installed_capacity: 18.3  # MW - 铝冶炼厂装机容量
    employment_per_mw: 15.4   # 人/MW - 每MW装机对应的就业人数
    display_name: "Aluminum Smelter"
    unit_system: "MW"
  
  Coal:
    installed_capacity: 328.0  # MW - 煤电装机容量
    employment_per_mw: 0.8     # 人/MW - 每MW装机对应的就业人数
    display_name: "Coal Power"
    unit_system: "MW"
  
  Gas:
    installed_capacity: 100.80  # MW - 天然气发电装机容量
    employment_per_mw: 0.2      # 人/MW - 每MW装机对应的就业人数
    display_name: "Gas Power"
    unit_system: "MW"

# 绘图配置
plot:
  figure_size: [12, 8]
  dpi: 150
  font_size: 18
  legend_font_size: 20
  title_font_size: 24
  axis_font_size: 24

# 颜色配置
colors:
  Aluminum Smelter: "#FF69B4"    # Hot pink
  Coal Power: "#000000"          # Black
  Gas Power: "#FF0000"           # Red

# 输出配置
output:
  directory: "results/employment_analysis"
